### ISSUE TITLE
funkcja obsługująca menu

### ISSUE THREAD

**Issue by redpeter** [redpeter/SAPER#11]

**Comment by kamills43** [comment]
#7 #13 Co myślicie o przechowywaniu w programie liczby bomb i nieodkrytych pól (w jakichś zmiennych) - nie musielibyśmy wtedy za każdym razem ich zliczać, co powinno nieco przyspieszyć nasz program?

**Comment by redpeter** [comment]
tak, to dobry pomysł. Chciałbyś to realizować przez zmienne globalne, czy przez wskaźniki?

**Comment by kamills43** [comment]
Zmienne globalne mogłyby być dość wygodne, chociaż nie są za bardzo eleganckie. Możemy się jutro zastanowić gdy będziemy planować kolejny sprint co i jak będziemy realizować, żeby nie narobić sobie problemów.
