### ISSUE TITLE
reakcja na odkrycie bomby

### ISSUE THREAD

**Issue by redpeter** [redpeter/SAPER#14]

**Comment by Tokarczk** [comment]
Czy może istnieć to obecnie w takiej wersji, a w momencie w którym zmieni się sterowanie kursorem, zostanie ona ulepszona?

**Comment by kamills43** [comment]
-> Po odkryciu bomby można by wyświetlić końcowy stan planszy.
-> Funkcja mogłaby zwracać boola: true jeśli jest bomba (bo nazywa się if bomb), false jeśli nie-bomba.

**Comment by redpeter** [comment]
Okej, zmianiłem tak, że już wyświetla stan końcowy planszy.
Myślę, że może zostać tak jak jest. Nie ma koniecznej potrzeby zmieniać na boola

**Comment by kamills43** [comment]
Potrzeby jako tako nie ma, to jest raczej kwestia przejrzystości czy czytelności kodu, raczej zadanie na wolną chwilę.
