### ISSUE TITLE
chorągiewki

### ISSUE THREAD

**Issue by redpeter** [redpeter/SAPER#15]
modyfikacja poprzedniego kodu, tak żeby można było zaznaczać przypuszczalne miejsca na bomby

**Comment by kamills43** [comment]
Wydaje mi się, że łatwiej będzie nam dodać tę funkcjonalność po dodaniu obsługi kursora w konsoli, dzięki czemu nie będziemy tracić dużo czasu na modyfikację kodu (tutaj musielibyśmy pytać, czy chcemy podać współrzędne do odkrycia czy zaznaczenia chorągiewką itd, a potem zdefiniujemy sobie 2 klawisze wprowadzające i sprawdzimy, który został naciśnięty). 
Same oznaczanie chorągiewkami nie jest nam chyba aż tak potrzebne na najbliższe 2-3 dni... Co o tym sądzicie?

**Comment by asias96** [comment]
Ja się jak najbardziej zgadzam :)

**Comment by redpeter** [comment]
tak, też popieram. W związku z tym przesuwam to na następny milestone

**Comment by kamills43** [comment]
chorągiewka w strukturze
- zmienne zakryte/ chorągiewki w menu()

**Comment by redpeter** [comment]
sprawdziłem, wszystko działa ;)
