### ISSUE TITLE
funkcja wypisująca tablicę

### ISSUE THREAD

**Issue by redpeter** [redpeter/SAPER#17]

**Comment by kamills43** [comment]
9 zlewają się z 0 w wyświetlanej tablicy, dodam opcję wyświetlania jakiegoś znaku (np. \* ) jako bomby.

**Comment by asias96** [comment]
hmmm, pozwolicie, ze zamiast zer dodam wyświetlanie spacji :)

**Comment by asias96** [comment]
Zrobione, wszystko działa jak należy
