### ISSUE TITLE
prace przygotowawcze

### ISSUE THREAD

**Issue by redpeter** [redpeter/SAPER#2]
założenie konta na serwisie GitHub, ściągnięcie repozytorium

**Comment by redpeter** [comment]
zadanie wykonałem, problemów żadnych nie miałem

**Comment by redpeter** [comment]
Zadanie wykonałem, konto założyłem, pobrałem i zainstalowałem gita i tortoisa, pobrałem aktualne repozytorium. Problemów żadnych nie miałem.

**Comment by kamills43** [comment]
U mnie podobnie, oprogramowanie działa, bez problemów.

**Comment by Tokarczk** [comment]
U mnie również :dancer:

**Comment by asias96** [comment]
Wszystko działa, zero problemów.
