### ISSUE TITLE
edycja funkcji Write oraz Test (użycie funkcji show)

### ISSUE THREAD

**Issue by redpeter** [redpeter/SAPER#20]

**Comment by kamills43** [comment]
Wydaje mi się, że czytelniej będzie, jeśli będziemy mieli inne znaczki na pola nieodkryte i zawierające 0. Można np. w pole nieodkryte wpisywać # (albo inny znaczek).

**Comment by asias96** [comment]
Przetestowane. Wszystko pięknie działa :D
