### ISSUE TITLE
Testy

### ISSUE THREAD

**Issue by kamills43** [redpeter/SAPER#25]
Znalezienie problemu pojawiającego się na poziomie ekspert i rozwiązanie go.

**Comment by kamills43** [comment]
Assigned:
@asias96 @kamills43

**Comment by kamills43** [comment]
Problem pojawia się, gdy trafiamy w bombę (nie zawsze - dlaczego?), tylko dla dużych plansz - poziom ekspert/ niestandardowy. Windows z jakiegoś powodu (pamięć?) ubija program.

**Comment by Tokarczk** [comment]
U mnie ten problem występuje już przy pierwszej bombie.

**Comment by kamills43** [comment]
U mnie też, a czy na małej planszy też?

**Comment by asias96** [comment]
Potwierdzam Kamil. Dla małych plansz jest wszystko okej, problem jest tylko z dużymi.

**Comment by asias96** [comment]
Problem nie pojawia się tylko gdy trafiamy w bombę, inną sytuacją jest np. powtórnym włączenie poziomu ekspert.

**Comment by kamills43** [comment]
Chyba nie jest to kwestia rozmiaru tablicy: dla tablicy 50x50 z 300 bombami działa ok.

**Comment by kamills43** [comment]
Błąd jest przy wczytywaniu wartości x i y: mamy zamienione zmienne :/

**Comment by asias96** [comment]
Wyłapałam jeszcze jeden inny błąd :P przy podawaniu w poziomie ekspert współrzędnych np. 29, 13 nie odkrywa tego pola. Mamy zamienione zmienne

**Comment by asias96** [comment]
No właśnie to poprawiam :)

**Comment by kamills43** [comment]
Wygląda na to, że problem jaki jest w ekspercie pojawia się dla nie-kwadratowych, dużych plansz.

**Comment by kamills43** [comment]
Tak, po zmianie domyślnych wartości na poziomie ekspert działa. Wydaje mi się, że zanim zaczniemy dalej coś robić warto by obkomentować wszystkie funkcje i może też nieoczywiste zmienne, przy okazji sprawdzając całość jeszcze raz.

**Comment by asias96** [comment]
Znalazłam błąd! (chyba) Jeszcze przetestuje czy to na pewno to i jeśli wszystko będzie działać to wstawiam. :)

**Comment by asias96** [comment]
Błąd w funkcji CreateArray, przyznaje się, mój błąd, (bo moja funkcja) albo małe niedopatrzenie, które zrobiło wielkie szkody... w pętli alokowana była pamięć idąc po col zamiast po row... mam nadzieję, ze teraz wszystko będzie działać :D

**Comment by kamills43** [comment]
Brawo! Wygląda na to, że działa :) Ale kolejne komentarze do kodu możemy i tak potem dodać, łatwiej będzie sobie poprzypominać co miała jaka funkcja robić.
