### ISSUE TITLE
Daily scrum 18-05-2016

### ISSUE THREAD

**Issue by Tokarczk** [redpeter/SAPER#41]

**Comment by redpeter** [comment]
W dniu dzisiejszym zmodyfikowałem funkcję PresKey, tak aby można było odznaczać flagę.
Zajęło mi to 10 min.
Problemów nie napotkałem.
W dniu jutrzejszym zajmę się blokadą odkrywania pól, które są oznaczone flagą.

**Comment by asias96** [comment]
Dzisiaj czytałam o dodawaniu kolorów w konsoli, dla tekstu i tła, a zdobytą wiedzę wykorzystałam do dodania w naszym programie kolorowego kursora. Zajęło mi to 25 min.
Jutro dopracuję i dodam inne kolory, by nasz saper był PIĘKNY! :D

**Comment by Tokarczk** [comment]
W dniu dzisiejszym poprawiłam drobne błędy, które zaburzały pełną sprawność pracy naszego programu.
Zajęło mi to 15 minut.
Nie napotkałam żadnych problemów.
Jutro zajmę się dalszymi ulepszeniami.

**Comment by kamills43** [comment]
Przepraszam za nieobecność wczoraj, wieczorem miałem drobne problemy techniczne z kompem. Wczoraj poprawiłem wyświetlanie planszy i usunąłem kilka drobnych błędów. Zajęło mi to 15 min. 
Problem, który się pojawił udało mi się na szczęście już usunąć więc wracam do pracy. Dzisiaj zajmę się dalszymi testami nowo dodanych oraz dotychczasowych funkcjonalności.
