### ISSUE TITLE
Daily scrum 19-05-2016

### ISSUE THREAD

**Issue by Tokarczk** [redpeter/SAPER#42]

**Comment by asias96** [comment]
W dniu dzisiejszym dodałam do naszego programu ulepszony, podświetlany za zielono kursor. Dodatkowo dodałam wyświetlanie kolorowych cyferek. Zajęło mi to 25 min. Nie napotkałam żadnych problemów.

**Comment by kamills43** [comment]
Dzisiaj zająłem się testowaniem gry i usunięciem znalezionego buga oraz dodałem wyświetlanie userowi informacji o działaniu poszczególnych klawiszy.
Zajęło mi to 10 min.
Jutro zacznę pisać sprawozdanie z realizacji naszego projektu.

**Comment by asias96** [comment]
Dzisiaj ulepszyłam w naszym programie wyświetlanie kursora. Dodatkowo dodałam kolorowe cyferki. Zajęło mi to 25 min. Żadnych problemów :)
Jutro zajmę się testowaniem naszego programu i pisaniem sprawozdania z realizacji naszego projektu.

**Comment by redpeter** [comment]
W dniu dzisiejszym wprowadziłem blokadę na odkrywanie pól, które są oznaczone jako flaga.
Zajęło mi to 10 min. 
Problemów nie napotkałem.
Jutro zajmę się testowaniem programu, oraz zacznę pisać sprawozdanie z realizacji projektu.

**Comment by Tokarczk** [comment]
Dzisiaj zamieniłam funkcjonalność wybranych klawiszy oraz wprowadziłam drobne zmiany wyświetlanej treści. 
Zajęło mi to około 10 minut. 
Jutro zajmę się testowaniem programu oraz pisaniem sprawozdania.
