### ISSUE TITLE
Daily scrum 20-05-2016

### ISSUE THREAD

**Issue by asias96** [redpeter/SAPER#44]

**Comment by kamills43** [comment]
Dzisiaj dodałem kilka drobnych poprawek do kodu (czytelność, międzyplatformowość) oraz opisałem w sprawozdaniu zasady gry w sapera. Zajęło mi to 15 minut, nie miałem problemów.
W poniedziałek będę w dalszym ciągu pracować nad sprawozdaniem i przeprowadzę kolejne testy naszej gry.

**Comment by asias96** [comment]
W dniu dzisiejszym poprawiłam wyświetlanie w naszym programie wykrzyknika oraz napisałam w sprawozdaniu jaki jest cel realizowanego projektu. Zajęło mi to 20 min.
W poniedziałek będę kontynuować testowanie i ulepszanie gry oraz dalej pracować nad sprawozdaniem.

**Comment by Tokarczk** [comment]
Dzisiaj zajęłam się testowaniem gry, ewentualnymi poprawkami komentarzy oraz ramami sprawozdania. Zajęło mi to 15 minut.
W poniedziałek przeprowadzę kolejne testy oraz będę pracować nad sprawozdaniem.

**Comment by redpeter** [comment]
W dniu dzisiejszym zacząłem pisać w sprawozdaniu opis działania w pierwszym dniu projektu. 
Zajęło mi to 15 min.
W poniedziałek będę kontynuował pisanie sprawozdania.
