### ISSUE TITLE
Daily scrum 23-05-2016

### ISSUE THREAD

**Issue by asias96** [redpeter/SAPER#45]

**Comment by kamills43** [comment]
Dzisiaj opisałem nasze plany na kolejne sprinty. Zajęło mi to 15 minut. Nie miałem żadnych problemów.
Jutro w dalszym ciągu będę pracować nad sprawozdaniem z naszego projektu.

**Comment by Tokarczk** [comment]
Dzisiaj opisałam podjęte działania podczas drugiego Milestone. Zajęło mi to 25 minut. 
Nie napotkałam żadnych problemów.
Jutro planuję pracować w dalszym ciągu nad sprawozdaniem z naszego projektu

**Comment by asias96** [comment]
W dniu dzisiejszym opisałam pierwszy sprint w naszym sprawozdaniu. Zajęło mi to 30 min. Nie napotkałam żadnych problemów.
Jutro będę kontynuować prace nad sprawozdaniem z projektu.

**Comment by redpeter** [comment]
W dniu dzisiejszym opisałem trzeci sprint naszego projektu. Zajęło mi to 15 min. Nie napotkałem żadnych problemów.
Jutro będę kontynuował pisanie sprawozdania.
