### ISSUE TITLE
Stworzenie struktury do planszy

### ISSUE THREAD

**Issue by kamills43** [redpeter/SAPER#5]
Stworzenie struktury z wartością bomb w otoczeniu. Jeżeli wartość ta jest równa 9 to w tym miejscu jest bomba. W strukturze powinny się też znaleźć wartość bool, względnie int z wartością prawda/fałsz czy dane pole jest już odkryte, czy nie.

**Comment by asias96** [comment]
Przetestowane! Wszystko działa. Super robota Kamil :)
