### ISSUE TITLE
Zliczanie bomb na planszy

### ISSUE THREAD

**Issue by kamills43** [redpeter/SAPER#7]
Funkcja licząca ile pozostało bomb na planszy.

**Comment by redpeter** [comment]
może od razu niech też wyświetli to ile tych bomb jest?

**Comment by asias96** [comment]
Według mnie to dobry pomysł, zwłaszcza, że informacja o ilości bomb jest właśnie dla użytkownika.

**Comment by kamills43** [comment]
No, dobry pomysł, chociaż może wyniknąć problem z tym, czy będzie nam wyświetlać taką informację w takim miejscu, w jakim będziemy chcieli, ale jeśli coś się zepsuje to po prostu wywalimy wyświetlanie z tej funkcji.

**Comment by asias96** [comment]
Jeśli wywołamy funkcję po wyświetleniu tablicy, a przed czyszczeniem ekranu to będzie idealnie. Pod planszą pokaże się komunikat o ilości bomb.

**Comment by asias96** [comment]
Funkcja przetestowana, wszystko działa, świetna robota! :)
