### ISSUE TITLE
Zmiana wartości pól w strukturach w zależności od liczby sąsiadujących bomb.

### ISSUE THREAD

**Issue by kamills43** [redpeter/SAPER#9]
Funkcja, która w tablicy zmienia odpowiednio wartość każdego pola (w strukturze) na odpowiednią wartość w zależności od liczby sąsiadujących bomb.

Ewentualnie można tą funkcję połączyć z funkcją losującą bomby

**Comment by redpeter** [comment]
Zmieniłem tylko w 80 linijce dwa warunki z > na >= ponieważ wychodziliśmy poza tablicę. Reszta jest w porządku :)
